# Base services for Indie Ventures
# Includes PostgreSQL and Nginx reverse proxy

services:
  # PostgreSQL - Shared database server
  postgres:
    image: supabase/postgres:15.8.1.085
    container_name: indie-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - indie-network

  # Nginx - Reverse proxy
  nginx:
    image: nginx:alpine
    container_name: indie-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/conf.d:ro
      - ./volumes/certbot/conf:/etc/letsencrypt:ro
      - ./volumes/certbot/www:/var/www/certbot:ro
      - ./volumes/logs/nginx:/var/log/nginx
    depends_on:
      - postgres
    networks:
      - indie-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Certbot - SSL certificate management
  certbot:
    image: certbot/certbot:latest
    container_name: indie-certbot
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
      - ./volumes/logs/certbot:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - indie-network

networks:
  indie-network:
    name: indie-network
    driver: bridge
